[build]
  publish = "."

[[redirects]]
  from = "/colonias/:slug/"
  to = "/colonias/:slug.html"
  status = 301

[[redirects]]
  from = "/colonias/:slug"
  to = "/colonias/:slug.html"
  status = 301


# Headers específicos para Netlify - complementa _headers
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"