[build]
  publish = "."

[[redirects]]
  from = "/colonias/:slug/"
  to = "/colonias/:slug.html"
  status = 301

[[redirects]]
  from = "/colonias/:slug"
  to = "/colonias/:slug.html"
  status = 301

# Headers de producción - Sin noindex
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"